"use strict";

export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_RECEIVED_SUCCESSFUL = "REQUEST_RECEIVED_SUCCESSFUL";
export const REQUEST_RECEIVED_ERROR = "REQUEST_RECEIVED_ERROR";

export const GOT_CHALLENGE = "GOT_CHALLENGE";
export const CLEAR_CHALLENGE = "CLEAR_CHALLENGE";
export const CHALLENGE_SUCCESS = "VICTORY!";
export const CHALLENGE_FAILURE = "FUCK.";
export const CHALLENGE_ERROR = "FUckkk.";